### ISSUE TITLE
Mockup Dojo Home Page

### ISSUE THREAD

**Issue by adorsk** [musikata/musikata.tracker#13]
Create dojo home page mockup.

**Comment by adorsk** [comment]
Here's another idea...based on the idea of a simple shomen/kamiza setup.
![dojo_home_sketch_kamiza](https://cloud.githubusercontent.com/assets/307075/2734780/608f32a2-c658-11e3-8cfa-aed9edbf1236.png)

A take-off of this idea would be to have a rack of musical instruments hanging...

**Comment by adorsk** [comment]
WRT to previous comment, something like this:
![dojo_home_sketch_musical_kamiza](https://cloud.githubusercontent.com/assets/307075/2735211/43547b02-c65d-11e3-8dd0-219d2ecc7eda.png)

This might be hard to pull off though...would be fun and kinda playful to do this (I had visions of changing the portrait every few weeks to our current favorite musician), but might need to wait until someone with better graphic design chops comes along.

**Comment by adorsk** [comment]
Another idea is to use an abstract zen image...no representation of a dojo at all. This could be fun because we could change the image every now and then. Or make zen paintings of instruments.

![dojo_home_zen_painting](https://cloud.githubusercontent.com/assets/307075/2735914/4a188448-c666-11e3-8863-b53df3e265c4.png)

**Comment by adorsk** [comment]
@zengardon Here's another take on the above, w/ image from here:
https://www.flickr.com/photos/ebarbaric/sets/72157627120413535/

![musikat_dojo_home_painting](https://cloud.githubusercontent.com/assets/307075/2742497/9744032a-c704-11e3-91e4-a767e42f5a35.png)

**Comment by zengardon** [comment]
Wow these are awesome. I really love the idea of having different instruments on the wall like you did here:
![dojo_home_sketch_musical_kamiza](https://cloud.githubusercontent.com/assets/307075/2735211/43547b02-c65d-11e3-8dd0-219d2ecc7eda.png)

To me this feels like the culmination of flavor: we are a dojo, and our tools/weapons are our instruments. That feels inspiring to me. Additionally, each instrument could be the entry point to the pathway – hovering over it highlights it and says 
**Way of the Drum**
_begin this journey_

once started,

**Way of the Drum**
_continue this path_
_2/3 challenges complete_

**Comment by zengardon** [comment]
the cricket might give your next challenge, and/or take you back to what you last worked on.

I'm working on a briefing for you of some of the best gamification techniques I've found. One trend I've noticed is always making it explicit what little thing you can work on for your next reward. The most motivating tools do the work of breaking up the big task into bite-sized chunks. You are NEVER left wondering what your next goal is, and it taps into a powerful desire for completion. Anything that shows 2/3 stars is exactly where we want to be: it's so close, it's doable, here's what you do next.

**Comment by adorsk** [comment]
Cool, glad you like the instrument rack idea. It was my favorite too.

Do you think it's good as silhouettes? I ask because it could take me a while to figure out to make good color illustrations. (Boy, I sure could use a cousin who is a graphic designer right now).

**Comment by zengardon** [comment]
I think the silhouettes are better than a bad graphic, but much worse than a good graphic. Maybe instead of illustrating from scratch we could collect existing woodcuts or archival pictures once we know what all the paths are and photoshop them into some consistency. Perhaps from [google art](http://www.google.com/culturalinstitute/browse) and I'll ask some Japanese studies friends. 

For some illustrations, we could consider [this paid service](https://swiftly.com/) that matches you with a designer for small tasks. They're well reviewed, and there might be some things that they're sufficiently good at to be worth it. But I don't know.

**Comment by zengardon** [comment]
Oh one other thing I would keep in mind is to [never use black](http://ianstormtaylor.com/design-tip-never-use-black/) :)

**Comment by adorsk** [comment]
Roger that on design stuff. Cool black article btw, even if the subject matter is a bit "dark" ;)

That swiftly service sounds interesting, I'll give that a shot to see how it works.

**Comment by adorsk** [comment]
@zengardon Saw your issue pruning, hope you're doing well!

**Comment by zengardon** [comment]
Thanks Alex! I finished my Ph.D. and am now working in science communication at Carnegie Mellon. Hope you’re doing well too!

best wishes,
Ardon
