### ISSUE TITLE
Figure out parameters to go from beginner to master for One Hand Clapping.

### ISSUE THREAD

**Issue by adorsk** [musikata/musikata.tracker#14]
Some pedagogical thoughts.

The goal of a learning path is to help people make the journey from beginning skills to mastery.
## Skill Parameters: Beginning to Advanced

One way to think of this journey is as a series of discrete steps ('stepping stones'). At each step, various skill parameters increase in difficulty.

Beginniner ---> Intermediate ---> Advanced.
### Skill Parameter Example: Tempo

For example, for tapping to a beat, one skill parameter is tempo (BPM). Beginners start out with BPMS close to average human heart rates (80ish BPM). Masters should be able to tap to a range of tempos, from slow to fast.  The path from beginner to master for tempo should thus chart a course from tempos centered around 80 BPM, to a wider range of tempos.

This path might look something like this:
1. 80 BPM
2. 75, 80, 85 BPM
3. 65, 70, 75, 80, 85, 90, 95 BPM
   x. ...
   n. 40, 50, .... 80, 90, ... 120 BPM
## Other Skill Parameters

For 'One Hand Clapping', we can think of several skill parameters:

| Parameter | Beginner | Advanced |
| --- | --- | --- |
| **Number of beats to tap** | fewer | more |
| **Accuracy** | less | greater |
| **Tempo** | closer to 80 BPM less variety |  |

Other parameters might include:
- **# of Slides**
- **Starting Health**

But I think those should be constant. As they affect the length of time of an individual training session.
## Plotting a Course

Now that we have some skill parameters outlined, how to plot a course that combines these parameters from beginner to master?

We can think of slicing up the parameter continuums into n discrete steps. N is the number of stepping stones we want to use.

Once we know the number of stones, we can then figure out ways to break them up into levels.

However, there are some things to consider here.
### Method A: Bump up _every_ parameter a little bit each time.

With this method, we increase every parameter together. For example, a path might look like this:

| Stone # | Tempos (BPM) | # of Beats to Tap | Accuracy Threshold |
| 1 | 80 | 4 | 50% |
| 2 | 75, 80, 85 | 6 | 40% |
| 3 | 70, 75 80, 85, 90 | 8 | 30% |
....
#### Advantages:
- easy to define path: just define endpoints and interpolate. Can computationally generate.
- easy to break into levels: just divide number of points by number of levels
- easy to test different options: can vary number of steps easily.
- easy to refine algorithmically based on data. Which might be more effective overall than human-defined path.
#### Disadvantages:
- is it effective? For example, does it help people understand the metacognition strategies needed to get better at the skill? e.g. "I need to work on my _accuracy_".
### Method B: Bump up _one or two_ parameters for each level.

With this method, we increase just one or two parameters at time. For example, a path might look like this:

| Stone # | Tempos (BPM) | # of Beats to Tap | Accuracy Threshold |
| 1 | 80 | 4 | 50% |
| 2 | 80 | 6 | 50% |
| 3 | 80 | 8 | 50% |
| 1 | 80 | 4 | 40% |
| 2 | 80 | 6 | 40% |
| 3 | 80 | 8 | 40% |

In this path we adjust _# of beats to tap_ first, and then _accuracy_. _Tempo_ stays constant.
#### Advantages:
- Might be easier for people to develop metacognition strategies?
- Can use badging to tie to specific skills e.g. 'You mastered medium tempos". (*Note: should ask Meghan B. at Pitt about this.)
#### Disadvantages:
- Is it harder to evaluate? Because paths are human defined, it's not quite so easy to compare one path to another. The field of possible paths is far wider.
- Requires more human curation: to determine what levels are, how many stones to use, which parameters to vary first.
- Can't computationally generate.
- Can't algorithmically refine. (or at least not in a way that I know of).

These are just some initial thoughts. Comments are welcome.

**Comment by adorsk** [comment]
@zengardon Starting some notes on pedagogy flow...see comment above this one.

**Comment by adorsk** [comment]
Thoughts on "skill badging" vs. "paced badging".

I think a few questions we need to answer for the path design include:
1. How long is it?
2. Where does it start?
3. Where does it end?
4. Where do we place rewards along the path?

One thing I'm realizing is that we don't know the answers to these questions. I suspect that the only way we can really find out is to try it.  So flexibility and assessment will be key, so that we can continually refine the path.

With this in mind, it makes me wonder if we should tie rewards to specific skill goals. For example, "You earned your Yellow Belt. This shows that you have mastered tempos ranging form 75 to 85 BPM." Let's call this "skill badging".

One alternative here is just to use rewards at regular intervals. So that rewards are related to general progress, rather than specific skill goals. For example, you get a belt every time you complete 3 stones along the path. Let's call this "pace badging".

I lean towards "pace bading", for a few reasons:
1. It seems more flexible. We can just adjust the intervals at which goals appear.
2. It seems like they can keep people better engaged. If we set up a regular train/reward process, with a predictable rate of reward, it could encourage people to keep going.

**Comment by adorsk** [comment]
Thoughts on what defines mastery of tapping skills.

I think that mastery is being able to tap with high accuracy, for x number of beats, for a given tempo.

I also think that people will perceive progress as being able to tap with greater accuracy. So they should never go back to a lower accuracy threshold for a given tempo.

With this in mind, I think vary number-of-beats first, accuracy second, and tempos third.

So that progress along the path looks like this:

| Stone # | BPM | # of Beats | Error Threshold (accuracy) |
| --- | --- | --- | --- |
| 1 | 80 | 4 | 50% |
| 2 | 80 | 8 | 50% |
| 3 | 80 | 4 | 40% |
| 4 | 80 | 8 | 40% |
| 5 | 80 | 4 | 30% |
| 6 | 80 | 8 | 30% |
| ... | ... | ... | ... |

**Comment by adorsk** [comment]
Meghan B. at Pitt sent me an interesting paper: 
http://www.lrdc.pitt.edu/schunn/research/papers/Abramovich-Schunn-Higashi.pdf

One of the things the paper mentions is that badging can help to increase personal interest. Especially for people who don't think they have natural skills or ability.

Consequently it may make sense to do at least some 'participatory badging'. This is badging that creates rewards based on participation or time spent, rather than on skill achievement.

**Comment by zengardon** [comment]
moving this to gameification (https://github.com/musikata/musikata.tracker/issues/16)
