### ISSUE TITLE
Path for rhythm based on dalcroze eurhythmics

### ISSUE THREAD

**Issue by zengardon** [musikata/musikata.tracker#17]
I met with that amazing music professor and we discussed what the first few rhythm lessons should cover. He doesn't know of anyone who's created a music skill map. He expressed a willingness to brainstorm again. My overall sense was that some things in rhythm have an established order, and then there are branching off points, depending on what he sees in the room (or in this case, individual student ability or choice). Here's how it begins:
- identifying the beat without meter - look for feelings of "lightness and heaviness"
- Walk to the beat. Walking taps into our natural experience of lightness and heaviness. This builds from the known to the unknown. BTW some iPhone apps like "moves" are getting very accurate at measuring steps.
- walk to the beat while introducing awareness of other things, such as changing direction on a cue, or hitting a button on a cue, or clapping. This is part of a continual process of learning how to direct attention and juggle competing stimuli. This is part of why walking is so great –  we can put it on autopilot or into awareness.
- Look for meter – i.e. establish that some beats have more heaviness. Start with 3/4 to reduce the options for heaviness
- Do something on the downbeat of 3/4 – change direction, clap, step
- Play with tempo – speed up and slow down. Look for feelings of momentum
- At this point you can introduce conducting, or switch into other meters like 4/4 and 2/4. The student should feel the sense of puzzlement and being off balance.
- Play with quick reactions. While walking the beat, also be receptive to a cue, like flashing red, which signals to do something, perhaps press a button? This is building an internalization of the beat, so you can continue to maintain it while directing your attention to other things
- Play with switching the cue. You want to fight laziness of not paying attention to the cue and going on autopilot. For example, the cue could become red + a sound. Then just the sound. This encourages the student to keep listening and maintain flexible attention

I feel like this would be a great accomplishment to adapt this far to online lessons. At that point I could see it being a viable prototype.

**Comment by adorsk** [comment]
A note from our earlier jam:

Some of these things might be tough to do as interactive exercises, but they could make good candidates for text interventions.

Or side stories during the main quest, a la the mini stories in Usagi Yojimbo.

**Comment by zengardon** [comment]
Yeah, I'm realizing eurhythmics may be hard to translate. See my review at https://github.com/musikata/musikata.tracker/issues/18

Motion is definitely hard to capture, and may not be appropriate for our limitations, especially on desktop. But hierarchy of attention exercises are still very applicable, and help get some rhythmic understanding to autopilot. A beginning exercise might be: tap the drum with the mouse, switch to tapping the space-bar on a cue. 
**Intermediate:** tap the downbeat on the mouse, other beats on spacebar. Then switch on cue.
**Advanced:** improvise a folk song while keeping beats. Listen to what you created – did you use rhythmic variety? Did it sound like it was moving towards a goal?
**Advanced:** do all of that while switching between 3/4 and 4/4 meter
**Expert:** press 6/8 and 4/4 meters at the same time in polyrhythm. Improvise a melody that shows you can change your focus at will to different meters.

This design space seems rather large to me, and can generate a ton of exercises that build up to what we actually do on a conservatory level

**Comment by adorsk** [comment]
I like these ideas.

A few folks have mentioned polyrhythms. Definitely makes me want to add more tap pads to 'One Hand Clapping'.

I hadn't thought of the different tapping emphases, like you mentioned in 'intermediate' above, that could be a cool use of multiple tap pads.

**Comment by zengardon** [comment]
# Identifying crusis

_The Sound of One Hand Clapping_

**Explore:**
listen to the drum at walking pace
tap along with the drum
after 4 beats see feedback

listen to a faster drum
tap along with the drum
after 4 beats see feedback

listen to a slow drum
tap along with the drum
after 4 beats see feedback

## Lightness and heaviness

_Lesson of the Monkey_

**SENSEI:** "Very good. 
Music is all around us, young grasshopper.
 Music is in the beat, 
 but it is also in the space 
 between the beat. 
 Silence can be music too."

**Animation:** monkey swinging from a branch from its tail in a pendulum motion.

"Consider the monkey, swinging in the tree. 
It has a beat too. 
It has moments of heaviness 
and moments of lightness. 
Not unlike our drum!"

**Animation:** a drum appears below the monkey, and the monkey hits the drum in the same slow tempo as before.

"Play again, young grasshopper. 
Tap the drum in time to the beat."

**Kata:** Tap the drum with monkey animation
after 4 beats see feedback in comparison to previous best.

## Conducting in 2

_Becoming the Monkey_

"Very good, young grasshopper. 
You will not always have a monkey 
to watch, you know. 
You must _become_ the monkey."

**Picture:** a conducting pattern in 2

"Let your hand become the monkey, 
falling down to a point of heaviness, 
rising to weightlessness, 
falling down again. 
Go on!"

"Perhaps it feels a little silly? 
Good! Life is silly! 
You must learn to become the monkey 
to keep the beat going inside of you. 
Only then will you play music 
in the space between the notes."

"You must practice your kata, young grasshopper. 
Let one hand swing like a monkey. 
Let the other hand tap the beat. 
This must become easy."

**Kata:** tap with drum, with animated monkey. Every 4 beats or so, give visual feedback

**A different angle:** think of the last time you were on a swing. You had a feeling of weightlessness at the top, and heaviness at the bottom.

"Are you ready to become the monkey?" 
I am ready / not yet
If not yet, "Keep training, young grasshopper"

"Very good. Goodbye monkey! 
Now let's see if you can 
become the monkey"

**Kata:** tap with drum, no monkey. Every 4 beats or so, give visual feedback

"Very good. Are you ready for your first test of skill?"
I am ready / not yet ("Keep training, young grasshopper")

"Let your hand become the monkey. 
Feel the moments of lightness and heaviness, 
and tap to the drum."

**Spar:** tap to the beat of different tempi
Show results, visual feedback, option to retake
Reward badge!
Option to share accomplishment and/or result on social media.

## Identify beat with music

_The monkey plays outside_

"You play very well with the drum, young grasshopper. 
Now you must learn to play without it!
Look for lightness and heaviness
And remember to become the monkey"

**Kata:** tap the drum with music
(note: the challenge here is to direct the user to tap every impulse. A distracting option could be every downbeat, so I would introduce a drum sound for a few beats before taking it away to set the tempo, and choose music where the downbeat isn't too much heavier than the rest of the beats)

"Very good. Are you ready for a test of skill?"
I am ready / not yet ("Keep training, young grasshopper")

**Spar:** tap the drum with music 
Show results, visual feedback, option to retake
Reward badge!
Option to share accomplishment and/or result on social media.

## Introducing 3

_Little drum joins the Dojo_

"Very very good. 
Tap along to the drum

**Explore:** Every third beat is a higher one, creating a downbeat in 3/4

"Yes, some beats are heavier than others. Tap to just the heaviest beat."

**Kata:** tap the downbeat
Visual feedback

 "Good. Music is not just one note, grasshopper – it is many.
  The time has come to add a new note to the Symphony of the Soul

 **Illustration:** use the Alt key to play the little drum

"Good. Use the little drum for the little beats!

 **Explore:** Play the little drum on the off beats
 (There is no big drum present, but the 3/4 pattern continues)

"Good. Now both together, hmm?

**Kata:** 3/4 beat. big drum on crusis, little drum on off-beats
visual feedback

**Kata:** repeat, for a few tempi

"Very good. Are you ready for a test of skill?"
I am ready / not yet ("Keep training, young grasshopper")

**Spar:** same thing. 3/4 beat. big drum on crusis, little drum on off-beats
Show results, visual feedback, option to retake
Reward badge!
Option to share accomplishment and/or result on social media.

## Introduction to flexible attention

_Lesson of the reed_ 

**Explore:** 3/4 beat. big drum on crusis, little drum on off-beats

At some point, the sensei pops up from the side of the screen and smacks you with a reed, saying "switch!" Let the user stumble.

"Aha! Now you must learn the lesson of the reed
Such a simple looking plant
with enormous flexibility
it bends, adapts, and does not break

"That which is stiff and does not yield
will snap under stress
that which is flexible will remain
You too must adapt
and train your mind for flexibility

**Explore:** 3/4. Little drum on crusis, big drum on off-beats

"Shall we try switching, hmm?"

**Kata:** 3/4. Big drum on crusis, little drum on off-beats. Every so often on the third beat, the sensei appears with a reed and says "switch!"

"Very good. Are you ready for a test of skill?"
I am ready / not yet ("Keep training, young grasshopper")

**Spar:** same thing.
Show results, visual feedback, option to retake
Reward badge!
Option to share accomplishment and/or result on social media.

## Conducting in 3

_Lesson of the frog_

"Swing like a monkey! Where do you think the heaviest part is?

**Explore:** A slow 3/4. Tap the little drum to the off-beats

**Animation:** monkey swings on the macro beat to show the answer

"There are a few other ways to move, and it's time to learn the way of the frog.

**Animation:** a frog jumps on lilli pads to make a conducted 3
**Image:** the conducted 3-pattern

"Very good. This too you must practice until you can become the frog.

**Kata:** A slow 3/4. Tap the little drum to the off-beats. Conduct in 3

"Remember the lesson of the reed: you must be flexible. Switch between the way of the frog and the way of the monkey

**Kata:** A slow 3/4. Tap the little drum to the off-beats. Conduct in a fast 3/4 or a slow 6/8

"Curious, isn't it?
The music feels different
but the music did not change
you changed, young grasshopper
pay attention to that feeling
music has a sound, yes,
but music also has a feel!

"it is the groove, the energy that flows
through all music
with practice and careful study, 
it will flow through you too

**Kata:** A slow 3/4. Tap the little drum to the off-beats. When a monkey appears, conduct in a fast 3/4
When a frog appears, conduct in a slow 6/8

Without a camera, there's no real way to test this, but you can see if the accuracy of the off-beats stays true.

**Comment by adorsk** [comment]
Very very cool!

This is great to see, not only because it helps us think about syllabus, but also because it shows us what UI elements we'll need (animations, pictures, music clips). Nice work w/ the markdown formatting, btw ;)

Not sure if you're looking for feedback/questions yet, but here are a few. Feel free to ignore these if you're still just sketching.

## Questions
- What's the difference between 'spar' and 'kata'? Is spar like a belt test?

## Random comments:
- Some things can be a bit tricky to code. Especially things that involve timing synchronization (animations, musical clip timing). Good thing we picked rhythm first, eh? ;)  With this in mind we should consider which of these we want to prioritize.
- I'm curious if these story path ideas will appeal to everyone. I think they're cool, but will other folks find them too cutesy? I'm wondering how we can test this out before we put a lot of time into working up the graphics. 
- I'm thinking how these story paths will fit into the overall flow of the site. Initially I had imagined Musikata as being closer to Duolingo (almost no story, mostly exercises with minimal instruction). But I kinda like the story paths. I'm thinking about if there's a way for story/exercise to live alongside each other. So that folks who want just training can get it (like more advanced musicians who want to train on polyrhythms), and folks who want story can get it.

**Comment by adorsk** [comment]
One other thing you might dig too is the Piano Safari stuff. The teacher guides have some cool ideas: http://pianosafari2.weebly.com/teacher-guides.html .

**Comment by zengardon** [comment]
"Kata" is practice, "Spar" is test. Feel free to change these. As I went along, it became useful to imagine three kinds of setups: **exploration,** which is free-form; **practice,** which is the test but without a grade and low stakes (though we would collect data) and **test,** which is evaluative and concludes a section.

I think synchronizing visuals with audio is important. What makes this hard? Can the animation be a video that includes sound on the right frame? Eurhythmics is very big on the importance of physical motion, so if I had to pick one thing it would be the swinging monkey – we can get a lot of milage out of that later on for introducing phrases. We could always just show the images of conducting patterns with a video of our hands.

Story paths is a big unknown. This might be something we have to experiment with, or do market research to get feedback. Note that it's not actually a story with a plot – I just took major concepts from lectures my professor would give the class, made them a little more poetic and in flavor. Each one serves a specific purpose and addresses a topic in music education. My intuition is that visual design will make or break this from being childish to interesting. As with any good game, you know it's not real, but it's fun and compelling to play in that world. The reaction I'm looking for is, "I've been playing with this website for getting music lessons online. It's cute. They're a "musical dojo" – a little silly, but I like it."

One way you could make this optional is by having each exercise start with just the instructions. On the side is the sensei character, who can visually indicate when he has something to say, but not say it until you click on him. In this model, it's there if you want it, but not mandatory or interrupting like clippy.

**Comment by adorsk** [comment]
Roger that on the terms. There's a fun term for free-form exercises in Aikido that you might like too, 'Randori'. In some versions of Randori, one person has to face down multiple attackers at once.  

(btw, There's a totally bad-ass video of Stephen Segal doing Randori here: https://www.youtube.com/watch?v=fH6HtkySiCQ)

Ah, I like the idea of the video animation, that could be a good solution. 

I think animations are only hard when you need to sync up user interaction with them (clicking or tapping). The reason for this is that the default javascript timing system is somewhat imprecise; to get good resolution we have to tap into the animation/audio clocks . There's a cool article about this here: http://www.html5rocks.com/en/tutorials/audio/scheduling/ . 

It's doable, it just takes some coding.

I'm warming up more and more to the story paths idea. I think part of my initial resistance is I'm not sure how to implement them yet, and I'm afraid of putting in a lot of code/design time up-front.

But it might not be as hard as I think it is. And in any case story paths should definitely be added at some point in Musikata's evolution. I'm just not sure if that point should be now.

In general I'm a bit blocked on what the next release goal should be. Got any good meta-process tips and how to think about this?

**Comment by adorsk** [comment]
Starting some meta-process thoughts in #25 .

**Comment by adorsk** [comment]
A variation on the story path idea in https://github.com/musikata/musikata.tracker/issues/10#issuecomment-43238303
