### ISSUE TITLE
An overview of the four schools of music pedagogy

### ISSUE THREAD

**Issue by zengardon** [musikata/musikata.tracker#18]
## Orff Schulwerk

The Orff approach encourages children to play with percussive instruments such as drums and xylophones to create a gentle and friendly environment.
#### Summary

Developed by German composer Carl Orff in the 1920's, the Orff approach combines music, movement, drama, and speech into lessons that are similar to a child's world of play. A core tenet is to treat music as a language that every child can absorb without formal instruction. Students are guided through stages of imitation, exploration, improvisation, and composition. In the classroom, the Orff approach stresses a low-pressure environment for performance, encourages enjoyment of making music, and invites parental participation. Teachers of Orff are guided by principles, not stepwise procedural methods. 
#### Applicability to online learning

It will be a challenge to create a playful learning environment without other people physically there. But computer games have  shown themselves to be great at immersive environments, free-form exploration may be good for the casual audience, and xylophones would be easy to implement on screen. The comparative lack of structure may limit the possibility of future adoption with conservatories. 
## Kodály Method

The Kodály Method is the most popular for singing, encoding musical information into syllables and hand signals while progressively increasing in difficulty.
#### Summary

Developed in Hungary during the mid-20th century by ethnomusicologist Zoltan Kodaly, the Kodály Method was inspired by listening to children sing folk songs. Children are introduced to musical concepts through listening, singing, or movement, then learn to connect them to simplified notation. The teacher introduces increasingly difficult concepts in accordance with the ability of the student, coupled with constant review. This method encodes musical information without using notation: duration is expressed by rhythm syllables, and pitches are expressed by movable-do solfege or scale degrees, as well as by hand signals. As a result, the method emphasizes oral learning and tonal function, which makes it very useful for choral singing and sight-singing. The classroom environment is comparatively strict.
#### Applicability to online learning

The core of Kodaly is a customized set of hand signs and syllables, so implementing this method would require tremendous work in visual and auditory recognition. Most computers are equipped with webcams and microphones, so the input is there, and it's hard for me to tell how hard it would be to recognize a limited set of oral and physical cues. If we find a person or company that can build the back end, we would benefit enormously from a more straightforward method that lends itself to badges of achievement, testability, and wide application: we could target people who want to learn to sing in the privacy of their homes, knowledgable musicians who want to drill sight-singing, and choral members who want to practice between rehearsal. Downside: mobile development might be harder, and less useful to people who don't want to sing.
## Suzuki Method

The Suzuki method focus on oral learning of a common curriculum, drawing praise and criticism for teaching thousands of students to play Fur Elise at an early age.
#### Summary

Developed by Japanese violinist Shin'ichi Suzuki in the mid-20th century, the Suzuki method is based in theory of language acquisition – that all people are capable of learning from the right environment. The Suzuki method is known for starting earliest (3-5 years old), learning by ear, and applied mostly to string instruments and piano. It uses pre-recorded music with a common repertoire to help students learn notes, phrasing, dynamics, rhythm, and tone quality by ear. This has the benefit of advancing students quickly, who typically play music much more advanced than they can read. The corollary is that the Suzuki method is commonly criticized for producing students with impoverished reading skills who tend towards rote learning and mechanistic performance at the expense of individual musicianship.
#### Applicability to online learning

Suzuki emphasizes playing actual musical instruments, so digital implementation has its work cut out, unless it's BYOMI. This was the method I learned under, and I often wish I hadn't. My aural skills are great, but the method does not emphasize understanding, which led me to seek other training; nor sight-reading, which came back to bite me. Playing advanced instrumental repertoire without understanding is the opposite of what I think we should be doing.
## Dalcroze Eurhythmics

Eurhythmics develops a deep understanding of rhythm and expressiveness through physical motion.
#### Summary

Developed by Swiss music educator Emile Jaques-Dalcroze in the early 20th Century, Eurhythmics emphasizes musical expression and understanding through kinesthetic physical awareness. Training consists of games for developing motor coordination and attention, such as walking, swinging the arms, and moving through space. Eurhythmics is notable for developing complex polyrhythmic skills, individual musical expressiveness, and improvisation.
#### Applicability to online learning

The bread and butter of Eurhythmics training is walking exercises. That technology may be there for the iPhone, but probably not the computer. I think the philosophy of music will translate well, and rhythmic dictation is a great skill to develop. But the rest of the training may focus too much on advanced performance skills to be useful to the casual audience.
# Synthesis

This project is pedagogically unusual for two reasons: 1) it wants to teach music, but without being performance-oriented 2) the use of technology makes some exercises harder, while opening up other new possibilities. It may behoove us to clarify our goals here: perhaps we can't offer the ability to play "twinkle twinkle little star" on a violin, but can instead show how that piece evolves musical ideas, and where it sits in the context of music history. This may necessitate the development of a new method of musical pedagogy for the internet era. Such a method might prioritize aural and cognitive analysis (transcription, Schenkerian analysis), supported by basic literacy (reading, transcription) and music appreciation (listening and writing about concert repertoire). 

Clarifying what we offer and what we don't has implications for future marketing and interested parties. People who might be interested in a more theory-based model include audience members who want to get more out of concerts (so market to orchestras), musicians who want to learn more theory, high schoolers preparing for the AP music theory exam (market to conservatory admissions), amateur composers (market with music software, youtube), people who want a deeper understanding of what's on the radio (advertise on radio, music stores, word of mouth). What we're offering the user – instead of tools of performance – is the tools to meaningfully engage with a thousand-year human tradition.

**Comment by adorsk** [comment]
This is my new favorite thread. Damn if you're not good at synthesis! Wikipedia, eat your heart out.

These summaries remind of another idea: the idea of providing a _platform_ for people to create (and test!) lessons themselves. I'll start another thread for this idea...  https://github.com/musikata/musikata.tracker/issues/19

With this in mind, we may want to think about whether we need to explicitly design exercises based on a methodology at the outset.

Though I do like the Eurythmics stuff. And it may be important to some people to understand the reasoning behind our lesson design. "What's the deal with this spinning firefly? Oh, it's based on Eurythmics? Ah, now I see why they include that. Awesome!"

**Comment by zengardon** [comment]
Thanks! I had fun writing this. Yeah I wonder if different animals could represent different schools of thought as well. As much as I love the firefly, it should probably be something that swings and represents physical pendulum-like motion. Perhaps a monkey swinging from a branch or jumping around.

kodaly is looking for something with singing, so maybe a songbird? I'm asking a friend of mine who teaches this method. [edit: she suggested a whale]

The path of structure might be the bee, with its highly organized honeycomb nest. Unless there's an animal that makes rounded bubble structures. Or a fish that jumps out of the water and lands to make a phrase. Or a grasshopper that can jump further.

Suzuki is listening and repeating, so maybe a parrot?

and Orff could be most anything friendly, like a panda

**Comment by adorsk** [comment]
Ha! These are fun to think about. Makes me wonder what a hungarian whale would sound like...
