### ISSUE TITLE
Bubble Diagrams

### ISSUE THREAD

**Issue by adorsk** [musikata/musikata.tracker#23]
Allow people to create and annotate interactive bubble diagrams, as per Ardon's TedX Talk: https://www.youtube.com/watch?v=cswhOCKQZ7Q

**Comment by adorsk** [comment]
@zengardon Putting links from our email thread here.

http://www.lipscomb.umn.edu/bubblemachine/
http://variations.sourceforge.net/vat/

**Comment by zengardon** [comment]
"The full Variations system is available as open source. To learn more and to download source or a demo client, visit the Variations site on SourceForge.

The Variations Audio Timeliner works independently of the Variations server using local audio files. This is now freely available for download as an open source product on SourceForge. To learn more and to download the program, visit the Variations Audio Timeliner site on SourceForge."

http://www.dlib.indiana.edu/projects/variations3/
http://www.dlib.indiana.edu/projects/variations3/software.html
http://variations.sourceforge.net/vat/
