### ISSUE TITLE
What to Put in Release?

### ISSUE THREAD

**Issue by adorsk** [musikata/musikata.tracker#25]
@zengardon 
I'm struggling with what to put in the next release.

The goal of this thread is to help clarify some thoughts around this.
## Release Goals

I'm thinking the primary goals of the next release are:
- fixes for #24 , based on feedback we received from earlier release
- to test the idea of 'paths'
- to test that paths along #24 actually help people improve their sense of rhythm
- to gain experience with data collection
- to prove overall viability by getting more sign-ups

Other things I should be considering here?
## Constraints

In thinking about how to meet these goals, I can think of a few constraints:
- Maintain integrity of the Musikata ideal (release only top-quality beautiful stuff that works)
- Coding time
- Graphic design time
- Cross-platform accessibility (desktop vs. mobile)
### Story Paths

Something that has come up recently is the idea of 'Story Paths' (a better term here?). These are paths that represent a journey through a set of different exercises/lessons, with a lot of emphasis on the metaphor/design. See discussion in #17 .

A few things I wrestle wrt StoryPaths:
- Are they feasible to do right now? (thinking about the graphic design work involved gives me some pause, b/c I think it could be considerable, and it would have to be _tight_ to make the metaphor work)
- Does implementing them help Musikata get more feedback and get closer to proving viability?

I have some initial resistance, and I still can't figure out why. A few reasons why I think I'm resisting, many of which are likely not rational:
- fear of time for coding/graphic design (fears may be exaggerated)
- different from original vision I had (Musikata as more like DuoLingo, almost pure exercise)
- not fully understanding flow through the StoryPath, how that ties in to exercises
- process of implementing StoryPath

More thoughts to come here...

**Comment by adorsk** [comment]
### Cross-Platform Accessibility Thoughts

I wonder if we should punt on supporting mobile platforms for now.

Seems like making audio/animation stuff on mobile could be tricky for now. Mainly because mobile processing speed is still fairly slow for these things.

With this in mind, perhaps we come back to mobile support when we are cranking with more team members and knowledge about how Musikata works.

#### Pros
- much easier to develop (don't need to worry so much about responsive design, processing speed, bundling for latency)
- fewer platforms to target (just safari, ffox, and chrome)

#### Cons
- Don't get information about what mobile interaction is like
- People might not try it out if they can only use it on desktop (?)

Right now I lean towards not supporting mobile. Because I think it will be difficult to make quality stuff that works on mobile w/ pure web stuff. I think we would need to use native apps to get good performance.

**Comment by adorsk** [comment]
Another idea we're exploring is 'questing' vs. 'training'.

I think of a 'questing' game as something more like http://codecombat.com . There are storylines and maps, everything in the game takes place in the context of the story.

I think of a 'training' game as something more like DuoLingo. There are some elements of metaphor, but most of the game takes place in training sessions. More like flash cards than an RPG game.

So far I had been thinking about Musikata as a 'training' game, rather than a 'questing' game.

I'm not sure yet if the two approaches make sense side-by-side, or if the switch between 'questing' and 'training' modes would be confusing.

**Comment by zengardon** [comment]
We should talk about training vs questing. I think you've hit the nail on the head with those descriptions, and this determines a lot of future work. I'm not wedded to anything, but I imagined it as a mix, leaning more towards questing. In any case, it's important to align vision and figure out resistance – your brain is telling you something. Don't "trust you gut," but by all means trust your amygdala.

## Things I think can be punted
- "I wonder if we should punt on supporting mobile platforms for now."
  I agree completely. This seems like a good example of spreading too thin, and multiplies the amount of work on your plate. People will be forgiving of a beta only working on desktop, and that lets us focus on more content.
- data collection is important, but not something the user will experience or benefit from. I would continue working on it, but it's not must-have for the release.
- Same with user signup and tracking. This is important, but a lot of work, delegatable, and not essential for testing

## Things I think should be highest priority to implement:
- use real music https://github.com/musikata/musikata.tracker/issues/1
- let people tap with spacebar https://github.com/musikata/musikata.tracker/issues/4
- redo if wrong https://github.com/musikata/musikata.tracker/issues/5
- the ability to add help text, whether for a storyline or something else, a la https://github.com/musikata/musikata.tracker/issues/6

## Lower priority that would be nice to have:
- button styling issue? https://github.com/musikata/musikata.tracker/issues/7
- allow people to miss a beat https://github.com/musikata/musikata.tracker/issues/9
- signup/login/backend data stuff

**Comment by adorsk** [comment]
Haha, if I trusted my gut right now Musikata would end up as a sushi website ;)

I think my Amygdala is leaning towards training. But I'm going to give it a few days to simmer.

Pretty glad this came up now, before we got too vested in one way. Definitely helping to clarify, and spur some thoughts about what interface should be like.

**Comment by adorsk** [comment]
Amygdala has come around. I'm back on board for story paths!

I was reading more through 'Reality is Broken'. At one bit it talks about how important 'game worlds' are. And how they work really well to encourage people when they feel epic and big. When people can explore, and be curious.

I think I was having trouble seeing how story paths & training (kata) would interact. I had pictured them as part of the same flow, interwoven with each other.

But now I think I see how they can exist side-by-side, as separate 'flows', with separate launchers on the dojo home screen, like this:

![kataandpaths](https://cloud.githubusercontent.com/assets/307075/3006103/7e87307e-de0a-11e3-92be-276455cd4ba7.png)

### Kata Flow

Kata exist as their own flow. A learner clicks 'train' on a kata launcher on the dojo home, and is taken right to a deck view. No path or anything. 

Instead there is a progress bar along the top with an 'experience points' (or something better in the metaphor) progress bar. When you successfully complete a slide, you get 10 experience points. Then, when you complete 100 experience points, you get the next belt.

You can optionally choose to test for the next belt at any time.

It might look something like this:

![deckwithstats](https://cloud.githubusercontent.com/assets/307075/3006104/8d28e578-de0a-11e3-8b07-8b62550a395f.png)

However, if it seems like someone isn't making progress, the sensei can suggest that they try the story path.

Experience points contribute to your character's overall experience points count, which lets you trick out your avatar in cool ways. A la HabitRPG.

## Story Path Flow

A learner clicks on story path  launcher on the dojo home, and is taken to an overworld view. The overworld view has 'levels'. Kind of like the Super Mario World overworld map. These levels can be info sessions, or little kata sessions.

It might look like this:
![storypath svg](https://cloud.githubusercontent.com/assets/307075/3006109/154a72c8-de0b-11e3-815d-2a8f0ae54bb7.png)

As you complete levels, you get experience points that contribute to your avatar's experience point count.

When you complete a story, the story might suggest that you keep training by using different kata. E.g. 'congratutions! You have completed way of the drum. Try training for 'yellow belt' in 'The Sound of One Hand Clapping'.

Or optionally, you might not be able to start certain sections of a story until you have a certain belt level in various kata. This could get a bit tricky, so not sure on that yet.

Still lots to think of here, but I'm feeling _much_ better about story paths now!

**Comment by adorsk** [comment]
See https://github.com/musikata/musikata.tracker/issues/10#issuecomment-43437824 for more on the kata flow.

**Comment by adorsk** [comment]
Thinking more about release stuff, and how to break this down.

One idea I'm thinking about is incremental releases for things which can be built up in pieces.

For example, for #17 , we could publish things in an order like this:
- the rhythm path overworld level (background image) + stone for 'the sound of one hand clapping'
- stone for 'lesson of the monkey'
- stone for 'becoming the monkey'
- ...
- more stones as we add them

This approach would be in contrast to developing all the stones, and releasing them in one batch.

Some advantages of incremental I can think of are:
- smaller units to think about & test
- learn more about release process
- get stuff out there sooner, for feedback

Some disadvantages are:
- might not be as flashy as a full release?
- might tweak things between releases (though this could be an advantage as well)
- might wear out our participation capital with early testers

To me, the advantages have it.  I'm not so concerned about the 'participation capital' issue, because I think some people will dig it, and want to follow it as it grows.

**Comment by adorsk** [comment]
In the meanwhile, while we think about this and start working up stuff for the the rhythm path, I'm going to work on getting the new version of the kata flow going (per https://github.com/musikata/musikata.tracker/issues/10#issuecomment-43437824) . This is something that can be released on its own, independently of the story paths.
